spring:
#  profiles:
#    active: @spring.profiles.active@
#  config:
#    activate:
#      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5433/my_diary
    username: 'postgres'
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8082
